puts "The students of my cohort at Makers Academy"

"------------------"
"Ruth Earle"
"Andy Gates"
"Marc Singh"
"Faisal Aydarus"
"Ethel Ng"
"Kevin Daniells"
"Maya Driver"
"Leapold Kwok"
"James Mcneil"
"Jerome Pratt"
"David Wickes"
"Javier Silverio"
"Elliot Lewis"
"Ben Tillet"
"Vincent Koch"
"Michelle Bellard"
"Nick Roberts"
"Tatiana Soukiassian"
"Mervé Silk"
"Albert Vallverdu"
"Lovis Schultze"
"Chris Oatley"
"Spke Lindsey"
"Henry Stanley"

print "Overall, we have " #{student_count} " great students"



